[build]
  command = "npm run build"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  included_files = ["views/**"]
  external_node_modules = [
    "axios",
    "cheerio",
    "ejs",
    "express",
    "serverless-http"
  ]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
